/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiuyukeji_ndk_config_HelloJni */

#ifndef _Included_com_xiuyukeji_ndk_config_HelloJni
#define _Included_com_xiuyukeji_ndk_config_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiuyukeji_ndk_config_HelloJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiuyukeji_ndk_1config_HelloJni_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
